-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS dwh.bridge_film_actor
(
    film_key integer NOT NULL,
    actor_key integer NOT NULL,
    CONSTRAINT pk_bridge_film_actor PRIMARY KEY (film_key, actor_key)
);

CREATE TABLE IF NOT EXISTS dwh.bridge_film_category
(
    film_key integer NOT NULL,
    category_key integer NOT NULL,
    category_weight numeric(5, 2) DEFAULT 1.00,
    CONSTRAINT pk_bridge_film_category PRIMARY KEY (film_key, category_key)
);

CREATE TABLE IF NOT EXISTS dwh.dim_actor
(
    actor_key integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    actor_id integer NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    full_name character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT dim_actor_pkey PRIMARY KEY (actor_key),
    CONSTRAINT uq_dim_actor_business UNIQUE (actor_id)
);

CREATE TABLE IF NOT EXISTS dwh.dim_category
(
    category_key integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    category_id integer NOT NULL,
    category_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_category_pkey PRIMARY KEY (category_key),
    CONSTRAINT uq_dim_category_business UNIQUE (category_id)
);

CREATE TABLE IF NOT EXISTS dwh.dim_customer
(
    customer_key integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    customer_id integer NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    full_name character varying(150) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    active_status character varying(20) COLLATE pg_catalog."default",
    location_key integer,
    create_date date,
    effective_start_date date,
    effective_end_date date,
    is_current boolean DEFAULT true,
    CONSTRAINT dim_customer_pkey PRIMARY KEY (customer_key),
    CONSTRAINT uq_dim_customer_business UNIQUE (customer_id)
);

CREATE TABLE IF NOT EXISTS dwh.dim_date
(
    date_key integer NOT NULL,
    full_date date NOT NULL,
    day_number integer NOT NULL,
    month_number integer NOT NULL,
    month_name character varying(20) COLLATE pg_catalog."default",
    quarter_number integer NOT NULL,
    year_number integer NOT NULL,
    day_name character varying(20) COLLATE pg_catalog."default",
    is_weekend boolean DEFAULT false,
    CONSTRAINT dim_date_pkey PRIMARY KEY (date_key),
    CONSTRAINT dim_date_full_date_key UNIQUE (full_date)
);

CREATE TABLE IF NOT EXISTS dwh.dim_film
(
    film_key integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    film_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    release_year integer,
    rating character varying(20) COLLATE pg_catalog."default",
    rental_duration integer,
    rental_rate numeric(10, 2),
    film_length integer,
    replacement_cost numeric(10, 2),
    special_features text COLLATE pg_catalog."default",
    language_key integer,
    effective_start_date date,
    effective_end_date date,
    is_current boolean DEFAULT true,
    CONSTRAINT dim_film_pkey PRIMARY KEY (film_key),
    CONSTRAINT uq_dim_film_business UNIQUE (film_id)
);

CREATE TABLE IF NOT EXISTS dwh.dim_inventory
(
    inventory_key integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    inventory_id integer NOT NULL,
    film_key integer NOT NULL,
    store_key integer NOT NULL,
    CONSTRAINT dim_inventory_pkey PRIMARY KEY (inventory_key),
    CONSTRAINT uq_dim_inventory_business UNIQUE (inventory_id)
);

CREATE TABLE IF NOT EXISTS dwh.dim_language
(
    language_key integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    language_id integer NOT NULL,
    language_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_language_pkey PRIMARY KEY (language_key),
    CONSTRAINT uq_dim_language_business UNIQUE (language_id)
);

CREATE TABLE IF NOT EXISTS dwh.dim_location
(
    location_key integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    address_id integer,
    address character varying(255) COLLATE pg_catalog."default",
    address2 character varying(255) COLLATE pg_catalog."default",
    district character varying(100) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default",
    postal_code character varying(50) COLLATE pg_catalog."default",
    phone character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dim_location_pkey PRIMARY KEY (location_key)
);

CREATE TABLE IF NOT EXISTS dwh.dim_staff
(
    staff_key integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    staff_id integer NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    full_name character varying(150) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    active_status character varying(20) COLLATE pg_catalog."default",
    store_key integer,
    location_key integer,
    effective_start_date date,
    effective_end_date date,
    is_current boolean DEFAULT true,
    CONSTRAINT dim_staff_pkey PRIMARY KEY (staff_key),
    CONSTRAINT uq_dim_staff_business UNIQUE (staff_id)
);

CREATE TABLE IF NOT EXISTS dwh.dim_store
(
    store_key integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    store_id integer NOT NULL,
    location_key integer,
    manager_staff_id integer,
    manager_staff_key integer,
    manager_full_name character varying(150) COLLATE pg_catalog."default",
    effective_start_date date,
    effective_end_date date,
    is_current boolean DEFAULT true,
    CONSTRAINT dim_store_pkey PRIMARY KEY (store_key),
    CONSTRAINT uq_dim_store_business UNIQUE (store_id)
);

CREATE TABLE IF NOT EXISTS dwh.fact_film_daily_snapshot
(
    snapshot_fact_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    snapshot_date_key integer NOT NULL,
    film_key integer NOT NULL,
    store_key integer NOT NULL,
    total_copies integer DEFAULT 0,
    available_copies integer DEFAULT 0,
    rented_copies integer DEFAULT 0,
    availability_rate numeric(5, 2),
    CONSTRAINT fact_film_daily_snapshot_pkey PRIMARY KEY (snapshot_fact_key)
);

CREATE TABLE IF NOT EXISTS dwh.fact_payment
(
    payment_fact_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    payment_id integer NOT NULL,
    rental_id integer,
    payment_date_key integer NOT NULL,
    customer_key integer NOT NULL,
    film_key integer,
    store_key integer,
    staff_key integer NOT NULL,
    customer_location_key integer,
    payment_amount numeric(10, 2) NOT NULL,
    payment_count integer DEFAULT 1,
    CONSTRAINT fact_payment_pkey PRIMARY KEY (payment_fact_key),
    CONSTRAINT uq_fact_payment_business UNIQUE (payment_id)
);

CREATE TABLE IF NOT EXISTS dwh.fact_rental
(
    rental_fact_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rental_id integer NOT NULL,
    rental_date_key integer NOT NULL,
    return_date_key integer,
    customer_key integer NOT NULL,
    film_key integer NOT NULL,
    inventory_key integer,
    store_key integer NOT NULL,
    staff_key integer NOT NULL,
    customer_location_key integer,
    rental_count integer DEFAULT 1,
    returned_count integer DEFAULT 0,
    rental_duration_days integer,
    expected_duration_days integer,
    late_return_flag boolean,
    late_days integer,
    active_rental_flag boolean DEFAULT false,
    CONSTRAINT fact_rental_pkey PRIMARY KEY (rental_fact_key),
    CONSTRAINT uq_fact_rental_business UNIQUE (rental_id)
);

ALTER TABLE IF EXISTS dwh.bridge_film_actor
    ADD CONSTRAINT fk_bridge_film_actor_actor FOREIGN KEY (actor_key)
    REFERENCES dwh.dim_actor (actor_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.bridge_film_actor
    ADD CONSTRAINT fk_bridge_film_actor_film FOREIGN KEY (film_key)
    REFERENCES dwh.dim_film (film_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.bridge_film_category
    ADD CONSTRAINT fk_bridge_film_category_category FOREIGN KEY (category_key)
    REFERENCES dwh.dim_category (category_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.bridge_film_category
    ADD CONSTRAINT fk_bridge_film_category_film FOREIGN KEY (film_key)
    REFERENCES dwh.dim_film (film_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.dim_customer
    ADD CONSTRAINT fk_dim_customer_location FOREIGN KEY (location_key)
    REFERENCES dwh.dim_location (location_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_dim_customer_location
    ON dwh.dim_customer(location_key);


ALTER TABLE IF EXISTS dwh.dim_film
    ADD CONSTRAINT fk_dim_film_language FOREIGN KEY (language_key)
    REFERENCES dwh.dim_language (language_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_dim_film_language
    ON dwh.dim_film(language_key);


ALTER TABLE IF EXISTS dwh.dim_inventory
    ADD CONSTRAINT fk_dim_inventory_film FOREIGN KEY (film_key)
    REFERENCES dwh.dim_film (film_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_dim_inventory_film
    ON dwh.dim_inventory(film_key);


ALTER TABLE IF EXISTS dwh.dim_inventory
    ADD CONSTRAINT fk_dim_inventory_store FOREIGN KEY (store_key)
    REFERENCES dwh.dim_store (store_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_dim_inventory_store
    ON dwh.dim_inventory(store_key);


ALTER TABLE IF EXISTS dwh.dim_staff
    ADD CONSTRAINT fk_dim_staff_location FOREIGN KEY (location_key)
    REFERENCES dwh.dim_location (location_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_dim_staff_location
    ON dwh.dim_staff(location_key);


ALTER TABLE IF EXISTS dwh.dim_staff
    ADD CONSTRAINT fk_dim_staff_store FOREIGN KEY (store_key)
    REFERENCES dwh.dim_store (store_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_dim_staff_store
    ON dwh.dim_staff(store_key);


ALTER TABLE IF EXISTS dwh.dim_store
    ADD CONSTRAINT fk_dim_store_location FOREIGN KEY (location_key)
    REFERENCES dwh.dim_location (location_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_dim_store_location
    ON dwh.dim_store(location_key);


ALTER TABLE IF EXISTS dwh.dim_store
    ADD CONSTRAINT fk_dim_store_manager_staff FOREIGN KEY (manager_staff_key)
    REFERENCES dwh.dim_staff (staff_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_film_daily_snapshot
    ADD CONSTRAINT fk_fact_snapshot_date FOREIGN KEY (snapshot_date_key)
    REFERENCES dwh.dim_date (date_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_snapshot_date
    ON dwh.fact_film_daily_snapshot(snapshot_date_key);


ALTER TABLE IF EXISTS dwh.fact_film_daily_snapshot
    ADD CONSTRAINT fk_fact_snapshot_film FOREIGN KEY (film_key)
    REFERENCES dwh.dim_film (film_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_film_daily_snapshot
    ADD CONSTRAINT fk_fact_snapshot_store FOREIGN KEY (store_key)
    REFERENCES dwh.dim_store (store_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_payment
    ADD CONSTRAINT fk_fact_payment_customer FOREIGN KEY (customer_key)
    REFERENCES dwh.dim_customer (customer_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_payment_customer
    ON dwh.fact_payment(customer_key);


ALTER TABLE IF EXISTS dwh.fact_payment
    ADD CONSTRAINT fk_fact_payment_customer_location FOREIGN KEY (customer_location_key)
    REFERENCES dwh.dim_location (location_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_payment
    ADD CONSTRAINT fk_fact_payment_date FOREIGN KEY (payment_date_key)
    REFERENCES dwh.dim_date (date_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_payment_date
    ON dwh.fact_payment(payment_date_key);


ALTER TABLE IF EXISTS dwh.fact_payment
    ADD CONSTRAINT fk_fact_payment_film FOREIGN KEY (film_key)
    REFERENCES dwh.dim_film (film_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_payment_film
    ON dwh.fact_payment(film_key);


ALTER TABLE IF EXISTS dwh.fact_payment
    ADD CONSTRAINT fk_fact_payment_rental FOREIGN KEY (rental_id)
    REFERENCES dwh.fact_rental (rental_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_payment
    ADD CONSTRAINT fk_fact_payment_staff FOREIGN KEY (staff_key)
    REFERENCES dwh.dim_staff (staff_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_payment_staff
    ON dwh.fact_payment(staff_key);


ALTER TABLE IF EXISTS dwh.fact_payment
    ADD CONSTRAINT fk_fact_payment_store FOREIGN KEY (store_key)
    REFERENCES dwh.dim_store (store_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_payment_store
    ON dwh.fact_payment(store_key);


ALTER TABLE IF EXISTS dwh.fact_rental
    ADD CONSTRAINT fk_fact_rental_customer FOREIGN KEY (customer_key)
    REFERENCES dwh.dim_customer (customer_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_rental_customer
    ON dwh.fact_rental(customer_key);


ALTER TABLE IF EXISTS dwh.fact_rental
    ADD CONSTRAINT fk_fact_rental_customer_location FOREIGN KEY (customer_location_key)
    REFERENCES dwh.dim_location (location_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_rental
    ADD CONSTRAINT fk_fact_rental_film FOREIGN KEY (film_key)
    REFERENCES dwh.dim_film (film_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_rental_film
    ON dwh.fact_rental(film_key);


ALTER TABLE IF EXISTS dwh.fact_rental
    ADD CONSTRAINT fk_fact_rental_inventory FOREIGN KEY (inventory_key)
    REFERENCES dwh.dim_inventory (inventory_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dwh.fact_rental
    ADD CONSTRAINT fk_fact_rental_rental_date FOREIGN KEY (rental_date_key)
    REFERENCES dwh.dim_date (date_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_rental_date
    ON dwh.fact_rental(rental_date_key);


ALTER TABLE IF EXISTS dwh.fact_rental
    ADD CONSTRAINT fk_fact_rental_return_date FOREIGN KEY (return_date_key)
    REFERENCES dwh.dim_date (date_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_rental_return_date
    ON dwh.fact_rental(return_date_key);


ALTER TABLE IF EXISTS dwh.fact_rental
    ADD CONSTRAINT fk_fact_rental_staff FOREIGN KEY (staff_key)
    REFERENCES dwh.dim_staff (staff_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_rental_staff
    ON dwh.fact_rental(staff_key);


ALTER TABLE IF EXISTS dwh.fact_rental
    ADD CONSTRAINT fk_fact_rental_store FOREIGN KEY (store_key)
    REFERENCES dwh.dim_store (store_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_fact_rental_store
    ON dwh.fact_rental(store_key);

END;